# Generated by Django 5.1.2 on 2024-11-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInstallation',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('capacity_ac', models.FloatField()),
                ('capacity_dc', models.FloatField()),
                ('tech_primary', models.CharField(max_length=50)),
                ('area', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='solar_solar_state_437343_idx'), models.Index(fields=['year'], name='solar_solar_year_d71b7a_idx'), models.Index(fields=['capacity_ac'], name='solar_solar_capacit_188bfd_idx')],
            },
        ),
    ]
